#!/bin/bash

code --install-extension 4tron.semantic-ui-snippets
code --install-extension alexdima.copy-relative-path
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension austenc.laravel-docs
code --install-extension austin.code-gnu-global
code --install-extension awesomektvn.toggle-semicolon
code --install-extension bengreenier.vscode-node-readme
code --install-extension benjpas.close-all
code --install-extension berublan.vscode-log-viewer
code --install-extension bibhasdn.git-easy
code --install-extension bibhasdn.unique-lines
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension buianhthang.xml2json
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension chrisdias.vscode-opennewinstance
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension codingyu.laravel-goto-view
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cybai.yaml-key-viewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbankier.vscode-quick-select
code --install-extension deerawan.vscode-faker
code --install-extension dkultasev.vs-code-snippet-generator
code --install-extension DmitryDorofeev.empty-indent
code --install-extension dongido.sync-env
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.jquerysnippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension funkyremi.vscode-google-translate
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension GregorBiswanger.json2ts
code --install-extension gurayyarar.editorenhancements
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hars.CppSnippets
code --install-extension HookyQR.beautify
code --install-extension ikappas.composer
code --install-extension JakeWilson.vscode-placeholder-images
code --install-extension jakob101.RelativePath
code --install-extension Janne252.fontawesome-autocomplete
code --install-extension jasonnutter.search-node-modules
code --install-extension jaycetyle.vscode-gnu-global
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension josee9988.minifyall
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension kameshkotwani.google-search
code --install-extension konstantin.wrapSelection
code --install-extension ksmithut.plusplus
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mikestead.dotenv
code --install-extension milkmidi.vs-code-quick-require
code --install-extension mkloubert.vscode-remote-workspace
code --install-extension mlewand.select-part-of-word
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension nathanchapman.JavaScriptSnippets
code --install-extension naumovs.color-highlight
code --install-extension NgekNgok.vscode-custom-snippets
code --install-extension NicholasHsiang.vscode-javascript-snippet
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension P-de-Jong.vscode-html-scss
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rafa-acioly.laravel-helpers
code --install-extension ramyaraoa.sass-helper
code --install-extension redhat.vscode-xml
code --install-extension ricardo-emerson.base-development-extensions-pack
code --install-extension rintoj.json-organizer
code --install-extension ritwickdey.LiveServer
code --install-extension royaction.color-manager
code --install-extension ryu1kn.partial-diff
code --install-extension sburg.vscode-javascript-booster
code --install-extension sdras.night-owl
code --install-extension Shan.code-settings-sync
code --install-extension shanoor.vscode-nginx
code --install-extension shardulm94.trailing-spaces
code --install-extension SimonSiefke.svg-preview
code --install-extension SirTori.indenticator
code --install-extension sleistner.vscode-fileutils
code --install-extension stef-k.laravel-goto-controller
code --install-extension tberman.json-schema-validator
code --install-extension tgreen7.vs-code-node-require
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension tiansin.vscode-laravel-assist
code --install-extension tuxtina.json2yaml
code --install-extension Tyriar.sort-lines
code --install-extension v4run.transpose
code --install-extension vincaslt.highlight-matching-tag
code --install-extension wayou.vscode-todo-highlight
code --install-extension whizkydee.material-palenight-theme
code --install-extension whtouche.vscode-js-console-utils
code --install-extension wmaurer.change-case
code --install-extension wmontalvo.vsc-jsonsnippets
code --install-extension wmontalvo.vsc-meta-snippet
code --install-extension yzhang.markdown-all-in-one